#!/usr/bin/env sh

raco test tests

if [ $? != 0 ]
then
    echo "Build failed!"
    exit 1
fi

RELEASE_DIR=release
rm -rf $RELEASE_DIR
mkdir $RELEASE_DIR

echo "Creating golemail..."
raco exe -o gm golemail.rkt
raco distribute $RELEASE_DIR/golemail gm
rm gm
echo "Done!"
